
services:
  user-service:
    build:
      context: ./backend/user-service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://0.0.0.0:27017/user-service
    depends_on:
      - mongo


  device-service:
    build:
      context: ./backend/device-service
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://0.0.0.0:27017/device-service
    depends_on:
      - mongo    

  
  api-gateway:
    build:
      context: ./backend/api-gateway
    ports:
      - "3008:3008"
    environment:
      - USER_SERVICE_URL=http://user-service:3001
    depends_on:
      - user-service

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: